version: '3.4'

services:
  shardeum-validator:
    container_name: shardeum-validator
    # network_mode: 'host'
    image: registry.gitlab.com/shardeum/server:dev
    volumes:
      - './config.json:/usr/src/app/config.json:Z'
      - './data/logs:/usr/src/app/logs:Z'
      - './data/db:/usr/src/app/db:Z'
    restart: 'always'
    env_file: .env
    ports:
      - '9001:9001'
      - '10001:10001'
